name: Update WordPress Page

on:
  push:
    branches:
      - main

jobs:
  update-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update WordPress Page
        env:
          WORDPRESS_URL: http://localhost/wordpress
          WORDPRESS_USERNAME: raymondlee
          WORDPRESS_APP_PASSWORD: rl88889999
        run: |
          PAGE_ID=$(curl -s -u "$WORDPRESS_USERNAME:$WORDPRESS_APP_PASSWORD" \
          "$WORDPRESS_URL/wp-json/wp/v2/pages?slug=sample-page" | jq -r '.[0].id')

          curl -X POST "$WORDPRESS_URL/wp-json/wp/v2/pages/$PAGE_ID" \
          -u "$WORDPRESS_USERNAME:$WORDPRESS_APP_PASSWORD" \
          -H "Content-Type: application/json" \
          -d '{
                "content": "Updated content from GitHub!",
                "title": "Updated Sample Page Title"
              }'
